name: Notify Discord on PR Merged to Develop

on:
  pull_request:
    types: [closed] # PR이 닫혔을 때 (병합 포함)
    branches:
      - main
      - develop # develop 브랜치로 PR 병합 시 감지

jobs:
  notify:
    if: github.event.pull_request.merged == true # 병합된 경우만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification (embed)
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_PR_URL }}
        run: |
          # PR_BODY가 없으면 기본 메시지 설정
          SAFE_BODY="${PR_BODY:-내용 없음}"

          # description 길이 제한 (Discord는 4096자 제한 있음)
          SAFE_BODY_TRUNCATED=$(echo "$SAFE_BODY" | head -c 3500)

          # jq를 사용하여 안전한 JSON 생성
          PAYLOAD=$(jq -n \
            --arg title "✅ PR Merged to \`$BASE_BRANCH\`! [PR 링크]" \
            --arg url "$PR_URL" \
            --arg desc "**Title:** $PR_TITLE\n**Author:** $PR_AUTHOR\n\n📝 **Description:**\n\`\`\`\n$SAFE_BODY_TRUNCATED\n\`\`\`" \
            '{
              embeds: [
                {
                  title: $title,
                  url: $url,
                  description: $desc,
                  color: 3066993
                }
              ]
            }')

          # 메시지 전송
          curl -v -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"